{"name": "Неуспешая авторизация с невалидной почтой", "status": "passed", "steps": [{"name": "Авторизовать пользователя", "status": "passed", "parameters": [{"name": "params", "value": "{'email': 'validation_failed@test.ru', 'password': 'rgonfuabrp'}"}], "start": 1733074893460, "stop": 1733074895405}], "parameters": [{"name": "invalid_email", "value": "'validation_failed@test.ru'"}], "start": 1733074893460, "stop": 1733074895407, "uuid": "fc9bdc18-2b2b-4e25-89d4-f7ddd8766e14", "historyId": "1654a550aa0e290165d55a34281976ac", "testCaseId": "51731a45c615c907cbf9824f6cfc2da4", "fullName": "tests.user.test_auth_login.TestAuthorizationUser#test_authorization_user_invalid_email", "labels": [{"name": "parentSuite", "value": "tests.user"}, {"name": "suite", "value": "test_auth_login"}, {"name": "subSuite", "value": "TestAuthorizationUser"}, {"name": "host", "value": "yutolstikova-3.local"}, {"name": "thread", "value": "6700-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.user.test_auth_login"}]}